CREATE TABLE IF NOT EXISTS item_daily (
  id INTEGER PRIMARY KEY,
  buy_delisted INTEGER,
  buy_listed INTEGER,
  buy_price_avg INTEGER,
  buy_price_max INTEGER,
  buy_price_min INTEGER,
  buy_price_stdev REAL,
  buy_quantity_avg INTEGER,
  buy_quantity_max INTEGER,
  buy_quantity_min INTEGER,
  buy_quantity_stdev REAL,
  buy_sold INTEGER,
  buy_value INTEGER,
  count INTEGER,
  timestamp INTEGER,
  sell_delisted INTEGER,
  sell_listed INTEGER,
  sell_price_avg INTEGER,
  sell_price_max INTEGER,
  sell_price_min INTEGER,
  sell_price_stdev REAL,
  sell_quantity_avg INTEGER,
  sell_quantity_max INTEGER,
  sell_quantity_min INTEGER,
  sell_quantity_stdev REAL,
  sell_sold INTEGER,
  sell_value INTEGER,
);
